[project]
name = "gss"
version = "gbv"
description = "Default template for PDM package"
authors = [
    {name = "curtcorum", email = "1796102+curtcorum@users.noreply.github.com"},
]
dependencies = []
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
